export const HttpStatus = {
   SUCCESS: 200,
   CREATED: 201,
   ACCEPTED: 202,
   NO_CONTENT: 204,
   BAD_REQUEST: 400,
   UNAUTHORIZED: 401,
   FORBIDDEN: 403,
   NOT_FOUND: 404,
   METHOD_NOT_ALLOWED: 405,
   CONFLICT: 409,
   INTERNAL_SERVER_ERROR: 500,
   NOT_IMPLEMENTED: 501,
   BAD_GATEWAY: 502,
   SERVICE_UNAVAILABLE: 503,
   GATEWAY_TIMEOUT: 504,
};

export const HttpMessage = {
   SUCCESS: 'Server response successful!',
   CREATED: 'Resource created successfully!',
   ACCEPTED: 'Request accepted!',
   NO_CONTENT: 'No content available!',
   BAD_REQUEST: 'Bad request!',
   UNAUTHORIZED: 'Unauthorized access!',
   FORBIDDEN: 'Forbidden access!',
   NOT_FOUND: 'Resource not found!',
   METHOD_NOT_ALLOWED: 'Method not allowed!',
   CONFLICT: 'Resource conflict!',
   INTERNAL_SERVER_ERROR: 'Internal server error!',
   NOT_IMPLEMENTED: 'Feature not implemented!',
   BAD_GATEWAY: 'Bad gateway!',
   SERVICE_UNAVAILABLE: 'Service unavailable!',
   GATEWAY_TIMEOUT: 'Gateway timeout!',
};
